/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-05-04 13:00:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nimbusds.jwt.SignedJWT;
import org.apache.commons.lang.StringUtils;
import org.apache.oltu.oauth2.client.response.OAuthAuthzResponse;
import org.wso2.sample.identity.oauth2.OAuth2Constants;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import org.apache.commons.codec.binary.Base64;

public final class oauth2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String code = null;
    String accessToken = null;
    String idToken = null;
    String name = null;
    String scope = null;
    String sessionState = null;
    String error = null;
    String grantType = null;
    String code_verifier = null;
    String code_challenge = null;

    boolean isOIDCLogoutEnabled = false;
    boolean isOIDCSessionEnabled = false;

    OAuthAuthzResponse authzResponse = null;

    try {
        String reset = request.getParameter(OAuth2Constants.RESET_PARAM);
        if (reset != null && Boolean.parseBoolean(reset)) {
            session.removeAttribute(OAuth2Constants.OAUTH2_GRANT_TYPE);
            session.removeAttribute(OAuth2Constants.ACCESS_TOKEN);
            session.removeAttribute(OAuth2Constants.CODE);
            session.removeAttribute(OAuth2Constants.ID_TOKEN);
            session.removeAttribute(OAuth2Constants.RESULT);
            session.removeAttribute(OAuth2Constants.SESSION_STATE);
            session.removeAttribute(OAuth2Constants.SCOPE);
            session.removeAttribute(OAuth2Constants.OAUTH2_AUTHZ_ENDPOINT);
            session.removeAttribute(OAuth2Constants.OIDC_LOGOUT_ENDPOINT);
            session.removeAttribute(OAuth2Constants.OIDC_SESSION_IFRAME_ENDPOINT);
            session.removeAttribute(OAuth2Constants.OAUTH2_PKCE_CODE_VERIFIER);
            session.removeAttribute(OAuth2Constants.OAUTH2_USE_PKCE);
        }

        sessionState = request.getParameter(OAuth2Constants.SESSION_STATE);
        if (StringUtils.isNotBlank(sessionState)) {
            session.setAttribute(OAuth2Constants.SESSION_STATE, sessionState);
        }

        error = request.getParameter(OAuth2Constants.ERROR);
        grantType = (String) session.getAttribute(OAuth2Constants.OAUTH2_GRANT_TYPE);
        if (StringUtils.isNotBlank(request.getHeader(OAuth2Constants.REFERER)) &&
                request.getHeader(OAuth2Constants.REFERER).contains("rpIFrame")) {
            /**
             * Here referer is being checked to identify that this is exactly is an response to the passive request
             * initiated by the session checking iframe.
             * In this sample, every error is forwarded back to this page. Thus, this condition is added to treat
             * error response coming for the passive request separately, and to identify that as a logout scenario.
             */
            if (StringUtils.isNotBlank(error)) { // User has been logged out
                session.invalidate();
                response.sendRedirect("index.jsp");
                return;
            } else {
                if (grantType != null && OAuth2Constants.OAUTH2_GRANT_TYPE_CODE.equals(grantType)) {
                    code = request.getParameter(OAuth2Constants.CODE);
                    session.setAttribute(OAuth2Constants.CODE, code);
                }
            }
        }

        if (grantType != null && OAuth2Constants.OAUTH2_GRANT_TYPE_CODE.equals(grantType)) {
            code = (String) session.getAttribute(OAuth2Constants.CODE);
            if (code == null) {
                authzResponse = OAuthAuthzResponse.oauthCodeAuthzResponse(request);
                code = authzResponse.getCode();
                session.setAttribute(OAuth2Constants.CODE, code);
            } else {
                accessToken = (String) session.getAttribute(OAuth2Constants.ACCESS_TOKEN);
                idToken = (String) session.getAttribute(OAuth2Constants.ID_TOKEN);
            }
        } else if (grantType != null && OAuth2Constants.OAUTH2_GRANT_TYPE_CLIENT_CREDENTIALS.equals(grantType)) {
            accessToken = (String) session.getAttribute(OAuth2Constants.ACCESS_TOKEN);
        } else if (grantType != null && OAuth2Constants.OAUTH2_GRANT_TYPE_RESOURCE_OWNER.equals(grantType)) {
            accessToken = (String) session.getAttribute(OAuth2Constants.ACCESS_TOKEN);
        }

        scope = (String) session.getAttribute(OAuth2Constants.SCOPE);
        if (StringUtils.isNotBlank(scope) && scope.contains(OAuth2Constants.SCOPE_OPENID)) {
            if (StringUtils.isNotBlank((String) session.getAttribute(OAuth2Constants.OIDC_LOGOUT_ENDPOINT))) {
                isOIDCLogoutEnabled = true;
            }

            if (StringUtils.isNotBlank((String) session.getAttribute(OAuth2Constants.OIDC_SESSION_IFRAME_ENDPOINT))) {
                isOIDCSessionEnabled = true;
            }
        }

    } catch (Exception e) {
        error = e.getMessage();
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>WSO2 OAuth2 Playground</title>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"\"/>\n");
      out.write("    <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js\"></script>\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><![endif]-->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/prettify.js\"></script>\n");
      out.write("    <!-- PRETTIFY -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/kickstart.js\"></script>\n");
      out.write("    <!-- KICKSTART -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/kickstart.css\" media=\"all\"/>\n");
      out.write("    <!-- KICKSTART -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" media=\"all\"/>\n");
      out.write("    <!-- CUSTOM STYLES -->\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function setVisibility() {\n");
      out.write("\n");
      out.write("            var grantType = document.getElementById(\"grantType\").value;\n");
      out.write("            var scope = document.getElementById(\"scope\").value;\n");
      out.write("\n");
      out.write("            document.getElementById(\"logutep\").style.display = \"none\";\n");
      out.write("            document.getElementById(\"sessionep\").style.display = \"none\";\n");
      out.write("\n");
      out.write("            if ('code' == grantType) {\n");
      out.write("                document.getElementById(\"clientsecret\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"callbackurltr\").style.display = \"\";\n");
      out.write("                document.getElementById(\"authzep\").style.display = \"\";\n");
      out.write("                document.getElementById(\"accessep\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"recownertr\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"recpasswordtr\").style.display = \"none\";\n");
      out.write("\n");
      out.write("                if (scope.indexOf(\"openid\") > -1) {\n");
      out.write("                    document.getElementById(\"logutep\").style.display = \"\";\n");
      out.write("                    document.getElementById(\"sessionep\").style.display = \"\";\n");
      out.write("                }\n");
      out.write("            } else if ('token' == grantType) {\n");
      out.write("                document.getElementById(\"clientsecret\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"callbackurltr\").style.display = \"\";\n");
      out.write("                document.getElementById(\"authzep\").style.display = \"\";\n");
      out.write("                document.getElementById(\"accessep\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"recownertr\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"recpasswordtr\").style.display = \"none\";\n");
      out.write("            } else if ('password' == grantType) {\n");
      out.write("                document.getElementById(\"clientsecret\").style.display = \"\";\n");
      out.write("                document.getElementById(\"callbackurltr\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"authzep\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"accessep\").style.display = \"\";\n");
      out.write("                document.getElementById(\"recownertr\").style.display = \"\";\n");
      out.write("                document.getElementById(\"recpasswordtr\").style.display = \"\";\n");
      out.write("            } else if ('client_credentials' == grantType) {\n");
      out.write("                document.getElementById(\"clientsecret\").style.display = \"\";\n");
      out.write("                document.getElementById(\"callbackurltr\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"authzep\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"accessep\").style.display = \"\";\n");
      out.write("                document.getElementById(\"recownertr\").style.display = \"none\";\n");
      out.write("                document.getElementById(\"recpasswordtr\").style.display = \"none\";\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function getAcceesToken() {\n");
      out.write("            var fragment = window.location.hash.substring(1);\n");
      out.write("            if (fragment.indexOf(\"&\") > 0) {\n");
      out.write("                var arrParams = fragment.split(\"&\");\n");
      out.write("\n");
      out.write("                var i = 0;\n");
      out.write("                for (i = 0; i < arrParams.length; i++) {\n");
      out.write("                    var sParam = arrParams[i].split(\"=\");\n");
      out.write("\n");
      out.write("                    if (sParam[0] == \"access_token\") {\n");
      out.write("                        return sParam[1];\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            return \"\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<!-- ===================================== END HEADER ===================================== -->\n");
      out.write("<body><a id=\"top-of-page\"></a>\n");
      out.write("\n");
      out.write("<div id=\"wrap\" class=\"clearfix\"/>\n");
      out.write("<!-- Menu Horizontal -->\n");
      out.write("<ul class=\"menu\">\n");
      out.write("    <li class=\"current\"><a href=\"index.jsp\">Home</a></li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("<div class=\"col_12\"/>\n");
      out.write("<div class=\"col_9\"/>\n");
      out.write("<h3>WSO2 OAuth2 Playground</h3>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("    <tr>\n");
      out.write("        <td>\n");
      out.write("            ");
 if (accessToken == null && code == null && grantType == null) {
                code_verifier = UUID.randomUUID().toString() + UUID.randomUUID().toString();
                code_verifier = code_verifier.replaceAll("-", "");

                MessageDigest digest = MessageDigest.getInstance("SHA-256");
                byte[] hash = digest.digest(code_verifier.getBytes(StandardCharsets.US_ASCII));
                //Base64 encoded string is trimmed to remove trailing CR LF
                code_challenge = new String(Base64.encodeBase64URLSafe(hash), StandardCharsets.UTF_8).trim();
                //set the generated code verifier to the current user session
                session.setAttribute(OAuth2Constants.OAUTH2_PKCE_CODE_VERIFIER, code_verifier);

            
      out.write("\n");
      out.write("            <div id=\"loginDiv\" class=\"sign-in-box\" width=\"100%\">\n");
      out.write("                ");
 if (error != null && error.trim().length() > 0) {
      out.write("\n");
      out.write("                <table class=\"user_pass_table\" width=\"100%\">\n");
      out.write("                    <tr>\n");
      out.write("                        <td><font color=\"#CC0000\">");
      out.print(error);
      out.write("\n");
      out.write("                        </font></td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("                ");
} 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"oauth2-authorize-user.jsp\" id=\"loginForm\" method=\"post\" name=\"oauthLoginForm\">\n");
      out.write("                    <table class=\"user_pass_table\" width=\"100%\">\n");
      out.write("                        <tbody>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Authorization Grant Type :</td>\n");
      out.write("                            <td>\n");
      out.write("                                <select id=\"grantType\" name=\"grantType\" onchange=\"setVisibility();\">\n");
      out.write("                                    <option value=\"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_CODE);
      out.write("\" selected=\"selected\">\n");
      out.write("                                        Authorization Code\n");
      out.write("                                    </option>\n");
      out.write("                                    <option value=\"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_IMPLICIT);
      out.write("\">Implicit</option>\n");
      out.write("                                    <option value=\"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_CLIENT_CREDENTIALS);
      out.write("\">Client\n");
      out.write("                                        Credentials\n");
      out.write("                                    </option>\n");
      out.write("                                    <option value=\"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_RESOURCE_OWNER);
      out.write("\">Resource\n");
      out.write("                                        Owner\n");
      out.write("                                    </option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Client Id : </label></td>\n");
      out.write("                            <td><input type=\"text\" id=\"consumerKey\" name=\"consumerKey\" style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"clientsecret\" style=\"display:none\">\n");
      out.write("                            <td><label>Client Secret : </label></td>\n");
      out.write("                            <td><input type=\"password\" id=\"consumerSecret\" name=\"consumerSecret\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"recownertr\" style=\"display:none\">\n");
      out.write("                            <td><label>Resource Owner User Name: </label></td>\n");
      out.write("                            <td><input type=\"text\" id=\"recowner\" name=\"recowner\" style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"recpasswordtr\" style=\"display:none\">\n");
      out.write("                            <td><label>Resource Owner Password : </label></td>\n");
      out.write("                            <td><input type=\"password\" id=\"recpassword\" name=\"recpassword\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Scope : </label></td>\n");
      out.write("                            <td><input type=\"text\" id=\"scope\" name=\"scope\" onchange=\"setVisibility();\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"callbackurltr\">\n");
      out.write("                            <td><label>Callback URL : </label></td>\n");
      out.write("                            <td><input type=\"text\" id=\"callbackurl\" name=\"callbackurl\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"authzep\">\n");
      out.write("                            <td>Authorize Endpoint :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"authorizeEndpoint\" name=\"authorizeEndpoint\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"accessep\" style=\"display:none\">\n");
      out.write("                            <td>Access Token Endpoint :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"accessEndpoint\" name=\"accessEndpoint\" style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"logutep\" style=\"display:none\">\n");
      out.write("                            <td>Logout Endpoint :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"logoutEndpoint\" name=\"logoutEndpoint\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"sessionep\" style=\"display:none\">\n");
      out.write("                            <td>Session Iframe Endpoint :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"sessionIFrameEndpoint\" name=\"sessionIFrameEndpoint\"\n");
      out.write("                                       style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr id=\"pkceOption\">\n");
      out.write("                            <td>Use PKCE</td>\n");
      out.write("                            <td><input type=\"radio\" name=\"use_pkce\" value=\"yes\">Yes &nbsp;\n");
      out.write("                                <input type=\"radio\" name=\"use_pkce\" value=\"no\" checked>No\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr id=\"pkceMethod\">\n");
      out.write("                            <td>PKCE Challenge Method</td>\n");
      out.write("                            <td><input type=\"radio\" name=\"code_challenge_method\" onchange=\"togglePKCEMethod()\"\n");
      out.write("                                       value=\"S256\" checked>S256 &nbsp;\n");
      out.write("                                <input type=\"radio\" name=\"code_challenge_method\" onchange=\"togglePKCEMethod()\"\n");
      out.write("                                       value=\"plain\">plain\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr id=\"pkceChallenge\">\n");
      out.write("                            <td>PKCE Code Challenge</td>\n");
      out.write("                            <td><input type=\"text\" style=\"width: 350px\" readonly name=\"code_challenge\"\n");
      out.write("                                       value=\"");
      out.print(code_challenge);
      out.write("\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr id=\"pkceVerifier\">\n");
      out.write("                            <td>PKCE Code Verifier [length : ");
      out.print(code_verifier.length());
      out.write("]</td>\n");
      out.write("                            <td><label>");
      out.print(code_verifier);
      out.write("\n");
      out.write("                            </label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"2\"><input type=\"submit\" name=\"authorize\" value=\"Authorize\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
} else if (code != null && accessToken == null) { 
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <form action=\"oauth2-get-access-token.jsp\" id=\"loginForm\" method=\"post\">\n");
      out.write("\n");
      out.write("                    <table class=\"user_pass_table\">\n");
      out.write("                        <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Authorization Code :</td>\n");
      out.write("                            <td>");
      out.print(code);
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Callback URL :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"callbackurl\" name=\"callbackurl\" style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Access Token Endpoint :</td>\n");
      out.write("                            <td><input type=\"text\" id=\"accessEndpoint\" name=\"accessEndpoint\" style=\"width:350px\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Client Secret : </label></td>\n");
      out.write("                            <td><input type=\"password\" id=\"consumerSecret\" name=\"consumerSecret\" style=\"width:350px\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 if (session.getAttribute(OAuth2Constants.OAUTH2_USE_PKCE) != null) {
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>PKCE Verifier : </label></td>\n");
      out.write("                            <td><input type=\"text\" id=\"pkce_verifier\" name=\"code_verifier\" style=\"width:350px\"\n");
      out.write("                                       value=\"");
      out.print((String)session.getAttribute(OAuth2Constants.OAUTH2_PKCE_CODE_VERIFIER));
      out.write("\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 }
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"submit\" name=\"authorize\" value=\"Get Access Token\"></td>\n");
      out.write("                            ");

                                if (isOIDCLogoutEnabled) {
                            
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <button type=\"button\" class=\"button\"\n");
      out.write("                                        onclick=\"document.location.href='");
      out.print((String)session.getAttribute(OAuth2Constants.OIDC_LOGOUT_ENDPOINT));
      out.write("';\">\n");
      out.write("                                    Logout\n");
      out.write("                                </button>\n");
      out.write("                            </td>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");

            } else if (accessToken != null) {

                if (idToken != null) {
                    try {
                        name = SignedJWT.parse(idToken).getJWTClaimsSet().getSubject();
                    } catch (Exception e) {
                        //ignore
                    }
            
      out.write("\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <form action=\"oauth2-access-resource.jsp\" id=\"loginForm\" method=\"post\">\n");
      out.write("\n");
      out.write("                    <table class=\"user_pass_table\">\n");
      out.write("                        <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Logged In User :</label></td>\n");
      out.write("                            <td><label id=\"loggedUser\">");
      out.print(name);
      out.write("</label></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Access Token :</label></td>\n");
      out.write("                            <td><input id=\"accessToken\" name=\"accessToken\" style=\"width:350px\" value=\"");
      out.print(accessToken);
      out.write("\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>UserInfo Endpoint :</label></td>\n");
      out.write("                            <td><input id=\"resource_url\" name=\"resource_url\" type=\"text\" style=\"width:350px\"/>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"submit\" class=\"button\" value=\"Get UserInfo\">\n");
      out.write("                            </td>\n");
      out.write("                            ");

                                if (isOIDCLogoutEnabled) {
                            
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <button type=\"button\" class=\"button\"\n");
      out.write("                                        onclick=\"document.location.href='");
      out.print((String)session.getAttribute(OAuth2Constants.OIDC_LOGOUT_ENDPOINT));
      out.write("';\">\n");
      out.write("                                    Logout\n");
      out.write("                                </button>\n");
      out.write("                            </td>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
} else { 
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <form action=\"oauth2-access-resource.jsp\" id=\"loginForm\" method=\"post\">\n");
      out.write("\n");
      out.write("                    <table class=\"user_pass_table\">\n");
      out.write("                        <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Access Token :</label></td>\n");
      out.write("                            <td><input id=\"accessToken\" name=\"accessToken\" style=\"width:350px\" value=\"");
      out.print(accessToken);
      out.write("\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 if (application.getInitParameter("setup").equals("AM")) { 
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Resource URL :</label></td>\n");
      out.write("                            <td><input id=\"resource_url\" name=\"resource_url\" type=\"text\" style=\"width:350px\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Introspection Endpoint :</label></td>\n");
      out.write("                            <td><input id=\"resource_url\" name=\"resource_url\" type=\"text\" style=\"width:350px\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"submit\" class=\"button\" value=\"Get TokenInfo\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            ");
} 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 } else if (grantType != null && OAuth2Constants.OAUTH2_GRANT_TYPE_IMPLICIT.equals(grantType)) {
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <form action=\"oauth2-access-resource.jsp\" id=\"loginForm\" method=\"post\">\n");
      out.write("\n");
      out.write("                    <table class=\"user_pass_table\">\n");
      out.write("                        <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Access Token :</label></td>\n");
      out.write("                            <td><input id=\"accessToken\" name=\"accessToken\" style=\"width:350px\"/>\n");
      out.write("                                <script type=\"text/javascript\">\n");
      out.write("                                    document.getElementById(\"accessToken\").value = getAcceesToken();\n");
      out.write("                                </script>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 if (application.getInitParameter("setup").equals("AM")) { 
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Resource URL :</label></td>\n");
      out.write("                            <td><input id=\"resource_url\" name=\"resource_url\" type=\"text\" style=\"width:350px\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Introspection Endpoint :</label></td>\n");
      out.write("                            <td><input id=\"resource_url\" name=\"resource_url\" type=\"text\" style=\"width:350px\"/>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"submit\" class=\"button\" value=\"Get TokenInfo\">\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function togglePKCEMethod() {\n");
      out.write("        var radios = document.getElementsByName('code_challenge_method');\n");
      out.write("        var pkceMethod = \"\";\n");
      out.write("        for (var i = 0, length = radios.length; i < length; i++) {\n");
      out.write("            if (radios[i].checked) {\n");
      out.write("                pkceMethod = radios[i].value;\n");
      out.write("                break;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        var pkceChallenge = document.getElementsByName(\"code_challenge\")[0];\n");
      out.write("        console.log(pkceMethod + \" \" + pkceChallenge.value);\n");
      out.write("        if (pkceMethod == \"S256\") {\n");
      out.write("            pkceChallenge.value = \"");
      out.print(code_challenge);
      out.write("\";\n");
      out.write("        } else if (pkceMethod == \"plain\") {\n");
      out.write("            pkceChallenge.value = \"");
      out.print(code_verifier);
      out.write("\";\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function pkceChangeVisibility(jQuery ) {\n");
      out.write("        if ($(\"#grantType\").val() == \"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_CODE);
      out.write("\" &&\n");
      out.write("                $(\"input[name='use_pkce']:checked\")[0].value == \"yes\") {\n");
      out.write("            $(\"#pkceMethod\").show();\n");
      out.write("            $(\"#pkceChallenge\").show();\n");
      out.write("            $(\"#pkceVerifier\").show();\n");
      out.write("\n");
      out.write("\n");
      out.write("            $(\"input[name='code_challenge_method']\")[0].removeAttribute('disabled');\n");
      out.write("            $(\"input[name='code_challenge_method']\")[1].removeAttribute('disabled');\n");
      out.write("            $(\"input[name='code_challenge']\")[0].removeAttribute('disabled');\n");
      out.write("        } else {\n");
      out.write("            $(\"#pkceMethod\").hide();\n");
      out.write("            $(\"#pkceChallenge\").hide();\n");
      out.write("            $(\"#pkceVerifier\").hide();\n");
      out.write("            $(\"#pkceOption\").hide();\n");
      out.write("\n");
      out.write("            $(\"input[name='code_challenge_method']\")[0].setAttribute('disabled', true);\n");
      out.write("            $(\"input[name='code_challenge_method']\")[1].setAttribute('disabled', true);\n");
      out.write("            $(\"input[name='code_challenge']\")[0].setAttribute('disabled', true);\n");
      out.write("        }\n");
      out.write("        if ($(\"#grantType\").val() == \"");
      out.print(OAuth2Constants.OAUTH2_GRANT_TYPE_CODE);
      out.write("\") {\n");
      out.write("            $(\"#pkceOption\").show();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    $( document ).ready(pkceChangeVisibility);\n");
      out.write("    //set form change handler.\n");
      out.write("    $(\"form[name='oauthLoginForm']\").change(pkceChangeVisibility)\n");
      out.write("</script>\n");

    if (isOIDCSessionEnabled) {

      out.write("\n");
      out.write("<iframe id=\"rpIFrame\" src=\"rpIFrame.jsp\" frameborder=\"0\" width=\"0\" height=\"0\"></iframe>\n");

    }

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
